#https://devdocs.prestashop.com/1.7/modules/concepts/services/
services:
    PrestaShop\Module\DemoProductForm\Form\Modifier\ProductFormModifier:
        class: PrestaShop\Module\DemoProductForm\Form\Modifier\ProductFormModifier
        arguments:
            - '@translator'
